// This file is the "source of truth" for sets and bindings indices
// and it dictates the descriptors layout for meshes
//
// Shaders and host code use this defines

//////// MESH VERTEX SHADER

#define MESH_VERT_IN_POSITION 0
#define MESH_VERT_IN_NORMAL 1
#define MESH_VERT_IN_TEX_COORDS 2

#define MESH_VERT_POSITION_OFFSET 0
#define MESH_VERT_POSITION_SIZE sizeof(glm::vec3)
#define MESH_VERT_NORMAL_OFFSET MESH_VERT_POSITION_OFFSET + MESH_VERT_POSITION_SIZE
#define MESH_VERT_NORMAL_SIZE sizeof(glm::vec3)
#define MESH_VERT_TEX_COORDS_OFFSET MESH_VERT_NORMAL_OFFSET + MESH_VERT_NORMAL_SIZE
#define MESH_VERT_TEX_COORDS_SIZE sizeof(glm::vec2)
#define MESH_VERT_STRIDE MESH_VERT_TEX_COORDS_OFFSET + MESH_VERT_TEX_COORDS_SIZE

#define MESH_VERT_OUT_POSITION 0
#define MESH_VERT_OUT_NORMAL 1
#define MESH_VERT_OUT_TEX_COORDS 2

//////// MESH FRAGMENT SHADER

#define MESH_FRAG_IN_POSITION MESH_VERT_OUT_POSITION
#define MESH_FRAG_IN_NORMAL MESH_VERT_OUT_NORMAL
#define MESH_FRAG_IN_TEX_COORDS MESH_VERT_OUT_TEX_COORDS

#define MESH_FRAG_OUT_COLOR 0

//////// MATERIAL BINDINGS

#define BINDING_SET_MATERIAL 0
#define FRAGMENT_BINDING_SAMPLER 0
#define FRAGMENT_BINDING_MATERIAL_ATTRIBUTES 1

//////// LIGHTS BINDINGS

#define BINDING_SET_LIGHTS 1
#define FRAGMENT_BINDING_LIGHTS 0

//////// MESH BINDINGS

#define BINDING_SET_MESH  2
#define VERTEX_BINDING_MODEL_VIEW_PROJECTION 0
