//
// Created by Matt Wang on 2019-11-08.
//

#ifndef BENDER_BASE_CONSTANTS_H
#define BENDER_BASE_CONSTANTS_H

#define MAX_MESHES 1000

#define MAX_MATERIALS 100
#define MAX_SAMPLERS_PER_MATERIAL 1
#define MAX_SAMPLERS MAX_MATERIALS * MAX_SAMPLERS_PER_MATERIAL
#define MAX_LINES_TEXTS 1

#define MAX_LIGHTS 100

#endif //BENDER_BASE_CONSTANTS_H
