#!/usr/bin/env python2

# Take logcats generated by the device_info app and extract device info JSON
# files.

from __future__ import print_function
import json
import os
import re

pattern = r'^.*device_info_json_proto\(\d+\): \[\d+:\d+\] (.*)'

# Process all logcat files
all_logcats = [fname for fname in os.listdir('.') if fname.endswith('_logcat')]

for filename in all_logcats:
    new_file = filename[:-6] + 'deviceinfo.json'
    print('{} -> {}'.format(filename, new_file))
    with open(filename) as f:
        json_chunk_lines = [
            line for line in f if 'device_info_json_proto' in line
        ]
    json_chunks = [
        re.match(pattern, line).group(1) for line in json_chunk_lines
    ]
    json_data = json.dumps(json.loads(''.join(json_chunks)), indent=4)
    with open(new_file, 'wt') as f:
        f.write(json_data)
